on command "tpps":
  set {loopnbr} to 1
  loop players:
    if {loopnbr} is 1:
      teleport %loop-player% to location(580, 70, 1661, world("world"), 0, 180
    if {loopnbr} is 2:
      teleport %loop-player% to location(538, 70, 1661, world("world"), 0, 180
    if {loopnbr} is 3:
      teleport %loop-player% to location(559, 70, 1682, world("world"), 0, 180
    if {loopnbr} is 4:
      teleport %loop-player% to location(559, 70, 1640, world("world"), 0, 180
    add 1 to {loopnbr}
    
